repos:
  - repo: https://github.com/ambv/black
    rev: '23.3.0'
    hooks:
    - id: black
      language_version: python3.8
      args: ["--line-length=150"]
  - repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
    - id: isort
      args: ["--multi-line=3", "--trailing-comma", "--force-grid-wrap=0","--use-parentheses", "--line-width=150"]